name: CI - test microservizio

on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout codice
        uses: actions/checkout@v3

      - name: Installa docker-compose
        run: |
          sudo curl -L \
            "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64" \
            -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version


      - name: Avvisa servizi con docker-compose
        run: docker-compose -f docker-compose.yml up -d

      - name: Attendi inizializzazione db
        run: sleep 10

      - name: Inizializza il db
        run: docker-compose -f docker-compose.yml exec microservizio python3 init_db.py


      - name: Esegui test
        run: docker-compose -f docker-compose.yml exec microservizio pytest 

      - name: Cleanup finale
        run: docker-compose -f docker-compose.yml down -v
          
